modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/Mrbysco/Spoiled/issues"
license="MIT"

[[mods]]
modId="spoiled"
version="${file.jarVersion}"
displayName="Spoiled"
displayURL="https://www.curseforge.com/minecraft/mc-mods/spoiled"
authors="Mrbysco, ShyNieke"
description='''
I'm sorry if I'm spoiling it for you. But you might wanna keep an eye on your food.
'''
[[dependencies.spoiled]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"